CREATE DATABASE LMS_DB
GO

USE LMS_DB;

CREATE TABLE AccountList (
	AccID INT IDENTITY(1,1) PRIMARY KEY,
	AccName NVARCHAR(MAX) NOT NULL,
	AccPass NVARCHAR(MAX) NOT NULL,
	AccRole NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Courses (
	CourseID INT IDENTITY(1,1) PRIMARY KEY,
	CourseName NVARCHAR(MAX) NOT NULL
);

CREATE TABLE CourseAssignment(
	AccID INT NOT NULL FOREIGN KEY REFERENCES AccountList(AccID),
	CourseID INT NOT NULL FOREIGN KEY REFERENCES Courses(CourseID)
);

CREATE TABLE CourseMaterials (
	CourseID INT NOT NULL FOREIGN KEY REFERENCES Courses(CourseID),
	Material NVARCHAR(MAX)
);

CREATE TABLE Quiz (
	QuizID INT IDENTITY(1,1) PRIMARY KEY,
	CourseID INT NOT NULL FOREIGN KEY REFERENCES Courses(CourseID),
	QuizName NVARCHAR(MAX) NOT NULL
);

CREATE TABLE QuizItems (
	ItemID INT IDENTITY(1,1) PRIMARY KEY,
	QuizID INT NOT NULL FOREIGN KEY REFERENCES Quiz(QuizID),
	CourseID INT NOT NULL FOREIGN KEY REFERENCES Courses(CourseID),
	QuestionDetail NVARCHAR(MAX),
	Choices NVARCHAR(MAX),
	Answer NVARCHAR(MAX)
);

CREATE TABLE Grades (
	AccID INT NOT NULL FOREIGN KEY REFERENCES AccountList(AccID),
	CourseID INT NOT NULL FOREIGN KEY REFERENCES Courses(CourseID),
	QuizID INT NOT NULL FOREIGN KEY REFERENCES Quiz(QuizID),
	Score INT NOT NULL
);
